remote_theme: granbom/jekyll-theme-bootstrap4-navbar-cdn
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: data<io>
description: data-centric workflows for Unity
